### PR TITLE
[ABORTED] Merge core package and add Typescript support

### PR DESCRIPTION
**Pull request by maxclaus**
Merge sqlectron-core package into this project so it simplifies the development since sqlectron-gui is the only project using it nowadays. As part of that change I converted the browser code to typescript and plan got the app ready for new Electron versions making it safer by not using remote anymore and using IPC calls instead.

## Planned work
* [x] Merge sqlectron-core merged into src/browser/core
* [x] Add Typescript support
* [x] Apply security improvements / Replace remote with IPC calls
* [x] Get initial window working after those changes
* [ ] Get database workspace working after those changes
* [ ] Test packaged app still working

## Out of scope
* Convert every src/renderer file to tsx: Only src/renderer/actions files are being converted to Typescript

### CODE REVIEW

**Comment by MasterOdin** [comment]
I am really not a fan of having big omnibus PRs like this that try to change a whole bunch of things all at once that are only really loosely connected to each other. It makes it hard to review and tons of new interactions and code paths.

Could we make a plan to focus on the three major bits of this in steps?

Like, within sqlectron-gui and sqlectron-core, let's convert the respective codebases to typescript. Then look to move from remote to ipc.invoke / ipc.handle, and then merging sqlectron-core into this codebase? That should hopefully make the PRs smaller and more manageable both to get done, and then review.

**Comment by maxcnunes** [comment]
Fair enough. I can do that.

**Comment by maxcnunes** [comment]
Aborted this PR, keeping it around while I break it down into smaller PRs.

**Comment by maxcnunes** [comment]
Closing this ticket because it has been broken into other tickets:
* https://github.com/sqlectron/sqlectron-gui/pull/588
* https://github.com/sqlectron/sqlectron-gui/pull/593

**Pull request closed without merging**
