### PR TITLE
Fix Edit Button for RECENTLY DUPLICATED / NEW CONNECTIONS

### PR DESCRIPTION
**Pull request by synle**
Refer to this issue for more details...
https://github.com/sqlectron/sqlectron-gui/issues/409

Below is a short description
Edit and Other commands don't work for RECENTLY DUPLICATED CONNECTIONS

1. duplicate an existing connection
2. try to edit it (notice it's not working)...

Connect button works, but the edit button doesn't work.

I'll check to see if I can send in a PR.

### CODE REVIEW

**Comment by synle** [comment]
Hold up, looks like there are some encryptions / decryptions not being set properly in `servers.items` compared with `config.data.servers`

screen shot 2017-12-22 at 1 47 46 pm

**Comment by synle** [comment]
Nvm, I think data within `servers.items` might have been decrypted already. This should work.

**Comment by synle** [comment]
Don't merge this yet. I think I found a bigger issue with our encryption and decryption logics when DUPLICATING, and UPDATING servers.

They don't work. Try to duplicate ABC, to ABC1, then ABC1 to ABC2, the encrypted passwords are not properly copied over, the same thing is true for Trying to edit / update the same connections multiple times.

**Comment by synle** [comment]
Look like the logic to encrypt passwords is encapsulated in the core library `sqlectron-core` and not exported.

So we might not be able to use `servers.items` directly.

**Comment by synle** [comment]
Okay guys, I finally ended up with the RELOAD after SAVING and after DUPLICATING path.

I think it's a safer path and solution to this problem.

**Comment by maxcnunes** [comment]
Good catch @synle. Thanks again 👏 👏 👏

**Pull request merged**
