### PR TITLE
:smile: Allow to search database items by their schemas

### PR DESCRIPTION
**Pull request by rodrigowirth**

### CODE REVIEW

**Comment by BornaP** [comment]
@rodrigowirth have you tested if searching tables without schemas (for DB engines like MySQL) still works with this change?

**Comment by rodrigowirth** [comment]
@maxcnunes I have just remove the packge-lock.json file 😄

**Comment by rodrigowirth** [comment]
Hi @BornaP, yes I have performed some tests using MySQL.

**Comment by maxcnunes** [comment]
Thanks Sir :)

**Pull request merged**
