### PR TITLE
Dark theme for body element (#384)

### PR DESCRIPTION
**Pull request by alexmylonas**
Suggestion for quick dark theme option.
Refactor for css and/or body element maybe is more suitable as a core change.

### CODE REVIEW

**Comment by maxcnunes** [comment]
@alexmylonas thanks for this PR. But there is an issue need to be fixed before I can accept it. After changing the theme it is not loading properly the main window:

**Comment by maxcnunes** [comment]
Sorry, I just noticed this was occuring on master and your PR #400 has fixed it. Thanks 👍

**Comment by maxcnunes** [comment]
That theme is not looking so good. But it is a good start. I will merge it and see if I can make a bit prettier. Thanks again!!

**Comment by alexmylonas** [comment]
Hi there! Yes, i agree it can be prettier if you have any suggestion i can try to improve it in the coming days!

**Comment by synle** [comment]
I looked at the PR, looks like you only change a few elements in CSS, might be a better choice if we have an app-wide black theme.

**Comment by synle** [comment]
After some works, I got some good successes, but we might need to adjust more custom components.

screen shot 2017-12-21 at 1 44 53 pm

screen shot 2017-12-21 at 1 46 44 pm


screen shot 2017-12-21 at 1 45 19 pm


screen shot 2017-12-21 at 1 46 47 pm

**Comment by synle** [comment]
Guys, I took a stab at it and here is my first PR for dark theme improvements.
https://github.com/sqlectron/sqlectron-gui/pull/408

@maxcnunes @alexmylonas

**Pull request merged**
