### PR TITLE
Add Option to Disable Splash Screen - Issue #426

### PR DESCRIPTION
**Pull request by barneydmedia**
Adds a checkbox in the settings menu to disable the startup animation, speeding up boot time for new windows.

### CODE REVIEW

**Comment by sscholle** [comment]
@barneydmedia I think you should add @maxcnunes as a Reviewer

**Comment by barneydmedia** [comment]
I don't think I have access to do that. Sorry if I missing something obvious.

**Comment by maxcnunes** [comment]
Hey @barneydmedia, you sent two good PRs. I'm adding you as a contributor, feel free to merge these changes and releasing a new version if you feel like doing that. Thanks!

**Comment by barneydmedia** [comment]
@maxcnunes Thanks for adding me, I'll work on getting a new build up sometime this week.

**Comment by barneydmedia** [comment]
@maxcnunes I don't have an Apple dev account, so I can't sign the binary. I may get one in the future, but for now I'm just going to keep fixing bugs. Let me know if I can do anything else to help.

**Comment by barneydmedia** [comment]
@maxcnunes I ran through the guide, but the build failed. From what I can tell in the log, it looks like the build just got hung up on downloading one of the assets or maybe binaries from AWS. Is there a way to restart the build and try again?

**Comment by maxcnunes** [comment]
There is a `re-build commit` at button
https://ci.appveyor.com/project/maxcnunes/sqlectron-gui/build/1.0.673. I
just triggered a new build.
Let me know if you can't see that button, I may need to change your role in
the project.

**Comment by barneydmedia** [comment]
@maxcnunes I wasn't able to see the button, but the rebuild you triggered completed successfully. I published the build and sent the PR to update the homebrew version.

**Pull request merged**
